#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression "Removing dependencies..."

# Remove metapackage and its dependencies

npm uninstall -g coffeescript
ynh_nodejs_remove

#=================================================
# REMOVE MULTIMEDIA SYMBOLIC LINK
#=================================================
ynh_script_progression "Removing Game folder..."

# Remove the app directory securely
ynh_safe_rm "/home/yunohost.multimedia/share/Game"
ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated nginx config
ynh_config_remove_nginx
if [ "$(ynh_app_setting_get --key=checksum__etc_nginx_mime.types)" == "$(md5sum "/etc/nginx/mime.types" | cut -d ' ' -f 1)" ]; then
	#file has not changed, restore the previous mime.type
	rm /etc/nginx/mime.types
	mv /etc/nginx/mime.types.$app /etc/nginx/mime.types
else
	#keep the actual mime.type and warn
ynh_print_warn "/etc/nginx/mime.types has changed! Keeping current file!"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
