#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

#backup & Update nginx MIME type so wasm mime type is recognized

if [ !$(grep wasm /etc/nginx/mime.types) ]; then
	ynh_print_info "/etc/nginx/mime.types saved as /etc/nginx/mime.types.$app"
	cp /etc/nginx/mime.types /etc/nginx/mime.types.$app
	ynh_replace --match="    application/octet-stream              bin exe dll;" --replace="    application/wasm                      wasm;\n\n    application/octet-stream              bin exe dll;" --file="/etc/nginx/mime.types"
	ynh_store_file_checksum "/etc/nginx/mime.types"
fi

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# SPECIFIC RESTORATION
#=================================================
# REINSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Reinstalling dependencies..."

# Define and install dependencies

npm install -g coffeescript

#=================================================
#SETTING MULTIMEDIA DIRECTORY
#=================================================
ynh_script_progression "Setting up Multimedia directory..."

ynh_multimedia_build_main_dir
mkdir -p $install_dir/assets/cores/Game
ynh_multimedia_addfolder --source_dir="$install_dir/assets/cores/Game" --dest_dir="/share/Game"
ynh_config_add --template="README.GAME" --destination="$install_dir/assets/cores/Game/README"
chmod 666 $install_dir/assets/cores/Game/README

#=================================================
# RESTORE USER RIGHTS
#=================================================

# Restore permissions on app files
chown -R www-data:multimedia $install_dir
# Requested so that multimedia group can see the Game folder : all parent folder should be readable by others
chmod 750 $install_dir

#=================================================
# RESTORE THE CRON FILE
#=================================================

ynh_restore "/etc/cron.d/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================
ynh_script_progression "Reloading nginx web server..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
