#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Downward Compatibility checks..."

#move from /opt/yunohost to /var/www : symbolic link will be remade by multimedia dir
if ynh_app_upgrading_from_version_before 1.15.0~ynh3; then
	if [ -L /home/yunohost.multimedia/share/Game ]; then
		#ynh_safe_rm "/home/yunohost.multimedia/share/Game"
		rm /home/yunohost.multimedia/share/Game #ynh_safe_rm does not remove link
	fi
fi
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#7z archive not handled by ynh and no way to strip component, have to move it manually
7zr x $install_dir/main -o$install_dir
#mv not working as target directory is not empty
cp -R $install_dir/retroarch/* $install_dir/
ynh_safe_rm "$install_dir/main"
touch $install_dir/analytics.js #https://github.com/libretro/RetroArch/issues/4539#issuecomment-473345195
#Get the indexer as exe so that folder w/ ROMs can be indexed
chmod +x $install_dir/indexer

# SETUP CRON FILE FOR INDEXER

#setup indexer bash script
ynh_config_add --template="indexer.sh" --destination="$install_dir/indexer.sh"
chown www-data: $install_dir/indexer.sh
chmod 744 $install_dir/indexer.sh
#setup cron file
cron_path="/etc/cron.d/$app"
ynh_config_add --template="retroarch.cron" --destination="$cron_path"

#=================================================
#SETTING MULTIMEDIA DIRECTORY
#=================================================
ynh_script_progression "Setting up Multimedia directory..."

ynh_multimedia_build_main_dir
mkdir -p $install_dir/assets/cores/Game
ynh_multimedia_addfolder --source_dir="$install_dir/assets/cores/Game" --dest_dir="/share/Game"
ynh_config_add --template="README.GAME" --destination="$install_dir/assets/cores/Game/README"
chmod 666 $install_dir/assets/cores/Game/README

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading dependencies..."

# Define and install dependencies
#Dependencies are not really required as this is just to unzip the 7z file
#However, npm IS required to run the coffeescript
ynh_nodejs_install

npm install -g coffeescript

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
